/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsIndexRouteImport } from './routes/tools/index'
import { Route as ToolsToolIDIndexRouteImport } from './routes/tools/$toolID/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsToolIDIndexRoute = ToolsToolIDIndexRouteImport.update({
  id: '/tools/$toolID/',
  path: '/tools/$toolID/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/tools/$toolID/': typeof ToolsToolIDIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tools': typeof ToolsIndexRoute
  '/tools/$toolID': typeof ToolsToolIDIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/tools/$toolID/': typeof ToolsToolIDIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tools/' | '/tools/$toolID/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tools' | '/tools/$toolID'
  id: '__root__' | '/' | '/tools/' | '/tools/$toolID/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
  ToolsToolIDIndexRoute: typeof ToolsToolIDIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/$toolID/': {
      id: '/tools/$toolID/'
      path: '/tools/$toolID'
      fullPath: '/tools/$toolID/'
      preLoaderRoute: typeof ToolsToolIDIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ToolsIndexRoute: ToolsIndexRoute,
  ToolsToolIDIndexRoute: ToolsToolIDIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
